### ISSUE TITLE
Random Color Generation Issue

### ISSUE THREAD

**Issue by typedefstructer** [ssloy/tinyraycaster#11]
Currently it is rand()%255 but it should be rand()%256, 
because of this 195841 colors will never be generated.

**Comment by ssloy** [comment]
Well, is that problematic? :)

**Comment by typedefstructer** [comment]
Not really, but I've seen % 255 in a lot of articles, that's why I had to post this.
BTW, Great Articles/Repos enjoying them all.

**Comment by ssloy** [comment]
yup, that is a mistake easy to make
